version: '3.8'
services:
  dev-db: # rename to - kken-crud-dev-db
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest
    networks:
      - kken
  test-db: # rename to - kken-crud-dev-db
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest
    networks:
      - kken
networks:
  kken: